### ISSUE TITLE
表現の修正

### ISSUE THREAD

**Issue by riki3004** [BattleFieldJapanCommunity/BFJUsersGuide#5]
各チャンネル紹介の「ステージチャンネル」のところの黒ポチ２つめ
「こちらのチャンネルは自由に使えることはできません。」を
「トレーラー鑑賞会などのイベント時のみこちらのチャンネルを利用することができます。」
に変更してください。

各チャンネル紹介の「低速モード」の
「低速モードがかかったチャンネルではメッセージを連続で送ることができません。」を
「低速モードがかかったチャンネルでは、メッセージを連続で送信することができません。」
に変更してください。

ファイル送信の「ファイル送信の際の注意事項」の２ポチめ
「逆の発展で、100MB以上はNitroを加入していても送れません。YouTubeやTwitterにあげることもオススメします。」を
「100MB以上はNitroに加入していても送信できません。YouTubeやTwitterに投稿し、リンクを共有することもオススメします。」
に変更してください。

ファイル送信の「Discordにおけるファイルの種類(一部)」の
「etc...」を消してください。

ボイスチャンネルの使い方の「ノイズ制御」の
「ノイズを抑制するDiscord本来の機能があります。」を
「Discordには、ノイズを制御する機能があります。」
に変更してください。

**Comment by merunno** [comment]
セキュリティの関係から依存関係の修正を最優先にするため、優先順位は低で作業します
